sudo: required

language: java
jdk: oraclejdk8

env:
  global:
    - secure: "sUcSDV+XLrNKH1rT+AhHIn9JOoB/a93uyJMM3ZkCid9trCI5jH5k0CBjoQNZ9BTWqu01TrcDiWK2Dhn6hW3HINmSy34bqMDHU1pvAu8tGWrdaIrDd/wbVBOHufJEL54QN5upfdOQqPZ589Xfh0qb74cJBN3aLDtQoFEpRFKPkLJ1dTe1Tf60SJ7sPQRSl7lg6+y263AOfrS59eBy5kDEk3eZvJ05Ye3Dw7gYR2X3t7uwM/CHi6UZKOBdFj2+7Z2i3pmO42uJa585yhRdt87ce5PvUSh4BQniEzWZ7+8HXsMkJnEU9qTEaHtOGz6ZMU8+Rl3f/XySQgG1IrItbhT29T8W5BWKfpJ5gXpd42nnUQRb7eugMIRVHntmlbhhZo2QNh4NH8NnZycWT2ScRbUUt3BNmg5zCb5JaKXoK/zN6w+fblvdydXB/XGprKCxwp/cNHINQhRf8Dbbg9SgMhKW5DNnyrwTDe2TO3y01/3mBViEhLiiBAXOqwN7jLmMMwCxmfRlQn9NedMnuYG7W7sL9MEDzHcgtIdVhvvY8KZ3tzQ0YKKS8fVA2cwFl9tYnPjVGn0EQzl5lcfuFQhiOBpDv+qWPvyCMp+71zgHdKntCQxfzQ5lT0jE76HPtiIhY1g1phMcvVYa20raOFgdmdyTl+8ZgLG8dkXGHloIkZJWRCU=" #SONAR
    - secure: "kwr1Gu7IhZGzlS94iNBQiDbIrvwVVF8ysRMAwwxPA3e+MV0yOdZ5aPOcOsgh8I6IbLcGquhIrBY7qKRRHtqftugVFqNOlRMhb41R/jI/aWB295paDNBAj+BXGTpfSlPRx90wHM/uVkJGqp2ig+wnQbkqqH9+xeadzdVxgQFe8o5+TP2SIYWBiiWdnhLH7bbTvewnj1a1EwvNXdEX2oHcCMq0qBdcT5RkrUgq/OUkwD6OaG5gxRIlDI0Htm3koZn9iqdnZfMQtLp1riK06RlWbgnB8n3LAc2j1PMryeBEnCR95OYmZ55aa77d7DC7X1/ybgTN/JT9vTQLmDDxnGTt80ubDDqwhfU6DUPs32AyxzR4/0UNFQF59LAArd+QHeukwuQhbFNt8ujuUcsSgRDnExPgBiga1GSLuZUC0YGitSw81MpgpzcEHrYwX3LlNGdz0hZuIA03Kvylp3ZK9asCgssfAQSqvYixGXTU0PnWE1eGUpO7cBZH1vVBvZ4l1PYV9G5zvxiua7AfMHjVHhzMKeAG907SBfwqALBniYfrGfRVhh/iJrPe5Qp0q3sVXYlZ/cuAAGSMGzHCnQCMWJAspu7g1EUyBtYXXlr4YlsYNogutf5U6mOMUFRtDiRX6sjbd/8Pwi1f/6GwzJyQj+uj/nJb/xy/IQMbJ8CI38Zfnm4=" #DOCKER_USER
    - secure: "bWg62YmESQFscbBbgvdwiTGDhKaLNUWvsBWd11ZdEdcm2Anh/30g5vSywUg5F2DAbVrdEMNtM0H4FFu7au3gM8NoWU8JRrqitSAOec2mxAjdS1GWojx/wQtU5aPp1MZOX1nV934LHJKonZzD4u7lQDJaHTv3NY/h1w1xbr8wy09MkGddhyeivj5rd9cz634Tkuhkn/Mv0/gsjDDi46VHj/Ny2jBa2CmDLvBWkljRiBqBIbfbs+ygES1q/PeyggXN/RhdGnHDoaOQOVru7Fg7bqzPMVUE2Q3QlmezTrQbBqRBjXtbg1qJbOVlJpdWLHyQ0+ATuJf6hjPL4grwk3DCUli14Q7IoXNrBpC86t87cmhyrbwXy8XpKZIcz/+Z0No6iHzmDnv2FsaEr/W563ShArFnzaOje2Z9J85KVzo3Go+m3g02ea+z5Cyxxiw2xwAYeezM9MHtDcrVVvgKWj2fyv9y34qi+LBJqq//+xVXFh4ntqZXX8JLBOxMBTVbZxPiXIp5vH3974YiicSB5gKrVMuu5dekVrcj13aD2AMdZkm34B/tXaan/0Mo00SsbEKRM95R0EjifRB/bPgmeIh/C6GX+h+qC5Yiwutio51fNI8B9N2u33XoY8lie864s70W9C3WqxkLcFQS3E/iVUBmr1IWllyVwRQp/4Dvn4Fkies=" #DOCKER_EMAIL
    - secure: "NgmA2BSSa/A+0Kc8NET8CtQaabyk+3vxhNIK/DH6xcORNtouIft6rfzqPmihFeqSbLB+2vA7UpgfA1r+feUZhe0Oqzgv+myygo2/uqV5af1WvlnIzAujVLCWFgyZ7IYCgYujOeX9gfVqBA4ehvvJmKw3ugLRVBceNVoV3WQCsMfcBxmutcVPtHQX9H+1xBynjDrJxn6AftA7WABW3BLH+EFqOYNQTOvYP0/foUk2zO5U822Y6AZnOpAH5Nt1BTagEaBEttyPN3Py3UsQigYgBqoCRwJfrrOX/tKnTIZcJwqxWBYrTGwEWru7wHHdZyq9NMJLsHmujBnXdH+8BnzfvWxrDITEW6VXODaDjvAcnX4LragpRHmhTUJkaxLgRAMue8VF5q9sG0umuUEZ2HBieYmn/tR4I8CatHZJFDse4GUAUqZbhJ3IYRTqUA75qkv9JuLq1E7ks+Pji0swbvCLengz8FRl9eSu/4hzfyPGKYzbOhd4AkW0XjnoK+al0jwhOKDX3/SK7F+RQh2Z4ieimFPSuFX6AYOVWu01r90xLnmS+nVrWk9KWcWpv5Y2Wf44nFnP89eRU+N6Uixh4B9hwaoOUIvVF7bOZF7xnboTeIgvA7AJDbdFDD5bj9nNKenqurhwPQCJxgmtz/gamnP/FSO6aGk/08eSFMMlmMDt5QQ=" #DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login --username $DOCKER_USER --password-stdin $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # JOURNAL SERVICE
  - export JOURNAL=rolandjurd/accounting-journal-service
  - docker build -t $JOURNAL:$COMMIT ./journal-service
  - docker tag $JOURNAL:$COMMIT $JOURNAL:$TAG
  - docker push $JOURNAL


addons:
  sonarcloud:
    organization: "roland-jurd-github"
    token:
      secure: $SONAR_TOKEN


script:
  - mvn sonar:sonar

services:
  - docker

